package MavenUnbalancedMessages.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'MavenUnbalancedMessages_Build'
accordingly, and delete the patch script.
*/
changeBuildType(AbsoluteId("MavenUnbalancedMessages_Build")) {
    params {
        add {
            param("111111", "1111111")
        }
    }
}
