package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.csharpFile
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'CsiTest_AutoDetectedBuild'
in the project with id = 'CsiTest', and delete the patch script.
*/
create(RelativeId("CsiTest"), BuildType({
    id("CsiTest_AutoDetectedBuild")
    name = "Auto detected build"

    vcs {
        root(RelativeId("CsiTest_GitGithubComBurnashevaCsiTestGitRefsHeadsMain"))
    }

    steps {
        csharpFile {
            path = "hello.world.csx"
            tool = "%teamcity.tool.TeamCity.csi.DEFAULT%"
        }
        csharpFile {
            path = "include.hello.world.csx"
            tool = "%teamcity.tool.TeamCity.csi.DEFAULT%"
        }
    }

    triggers {
        vcs {
        }
    }
}))

