package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'MavenUnbalancedMessagesCopy_Build'
in the project with id = 'MavenUnbalancedMessagesCopy', and delete the patch script.
*/
create(RelativeId("MavenUnbalancedMessagesCopy"), BuildType({
    id("MavenUnbalancedMessagesCopy_Build")
    name = "Build"

    vcs {
        root(RelativeId("MavenUnbalancedMessagesCopy_HttpsGithubComBurnashevaMavenUnbalancedMessagesGitRefsHeadsMaster"))
    }

    steps {
        maven {
            goals = "clean test"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
        }
    }

    triggers {
        vcs {
        }
    }
}))

