package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_1.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'SbtHelloworld13_CopyBuild'
in the project with id = 'SbtHelloworld13', and delete the patch script.
*/
create(RelativeId("SbtHelloworld13"), BuildType({
    id("SbtHelloworld13_CopyBuild")
    name = "Copy Build"

    params {
        param("q", "q")
    }

    vcs {
        root(RelativeId("SbtHelloworld13_HttpsGithubComBurnashevaSbtHelloworld13gitRefsHeadsMaster"))
    }

    steps {
        step {
            type = "SBT"
        }
    }

    triggers {
        vcs {
        }
    }
}))

