package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'CsiTest_GitGithubComBurnashevaCsiTestGitRefsHeadsMain'
in the project with id = 'CsiTest', and delete the patch script.
*/
create(RelativeId("CsiTest"), GitVcsRoot({
    id("CsiTest_GitGithubComBurnashevaCsiTestGitRefsHeadsMain")
    name = "git@github.com:burnasheva/csi_test.git#refs/heads/main"
    url = "git@github.com:burnasheva/csi_test.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = defaultPrivateKey {
        userName = "git"
    }
}))

